### ISSUE TITLE
Breaking API change in discordgo

### ISSUE THREAD

**Issue by iopred** [GoGerard/GerardDiscord#10]
Hey,

In:
https://github.com/bwmarrin/discordgo/blob/594d27626eb3049b32ad1d8e9b7a289501a41e0c/wsapi.go#L161

I changed it so the heartbeat is always started, this fixes bugs such as this:
https://github.com/mammothbane/discord-jukebox/blob/master/bot.go#L30

The side effect is your code will be sending 2 heartbeats, which will break.
The fix is to remove this line:
https://github.com/GoGerard/GerardDiscord/blob/master/events.go#L188

I'll send a pull request if you are not interested in fixing this!

Thanks!

**Comment by bwmarrin** [comment]
Also, see this issue which once implemented will keep this from being a breaking change.
https://github.com/bwmarrin/discordgo/issues/43

**Comment by bwmarrin** [comment]
Just FYI v0.8.0 is now released and pushed to master for Discordgo.
